### GET request to example server
GET http://localhost:8080/api/nearest-place?lat=54.380395&lon=18.608007&type=place_of_worship
###

### GET request to example server
GET http://localhost:8080/api/all-places?lat=54.380395&lon=18.608007&type=place_of_worship&radius=2000
###

### GET request to example server
GET http://localhost:8080/api/all-places/save?lat=54.380395&lon=18.608007&type=place_of_worship&radius=2000
###

### GET request to example server
GET http://localhost:8080/api/get-amenity-list?lat=54.380395&lon=18.608007
###

### ATM
GET http://localhost:8080/api/scan-gdansk?type=atm
###
### HOSPITAL
GET http://localhost:8080/api/scan-gdansk?type=hospital
###
### SCHOOL
GET http://localhost:8080/api/scan-gdansk?type=school
###
### RESTAURANT
GET http://localhost:8080/api/scan-gdansk?type=restaurant
###
### PLACE OF WORSHIP
GET http://localhost:8080/api/scan-gdansk?type=place_of_worship
###
### LIBRARY
GET http://localhost:8080/api/scan-gdansk?type=library
###
### SUPERMARKET
GET http://localhost:8080/api/scan-gdansk?type=supermarket
###
### CINEMA
GET http://localhost:8080/api/scan-gdansk?type=cinema
###

### HEATMAP
GET http://localhost:8080/api/heatmap
###